# permissions for end users to edit schedulercanaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schedulercanary-editor-role
rules:
- apiGroups:
  - monitoring.appuio.io
  resources:
  - schedulercanaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.appuio.io
  resources:
  - schedulercanaries/status
  verbs:
  - get
