apiVersion: monitoring.appuio.io/v1beta1
kind: SchedulerCanary
metadata:
  name: schedulercanary-sample
spec:
  interval: 1m
  maxPodCompletionTimeout: 3m
  podTemplate:
    metadata:
      labels: {}
    spec:
      containers:
      - command:
        - sh
        - -c
        args:
          - date;sleep 5;date
        image: curlimages/curl:7.84.0
        name: my-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
