apiVersion: monitoring.appuio.io/v1beta1
kind: SchedulerCanary
metadata:
  name: schedulercanary-exit-err
spec:
  podTemplate:
    metadata:
      labels: {}
    spec:
      containers:
      - command:
        - sh
        - -c
        args:
          - |-
            date
            sleep 5
            false
        image: busybox
        imagePullPolicy: Always
        name: my-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
